### PR TITLE
drop em support

### LINKED ISSUE #2: make output unit an option (some people prefer px)

### PR DESCRIPTION
**Pull request by nelsonpecora**
fixes #2

### CODE REVIEW

**Comment by gloddy** [comment]
Isn't em the best practice?

**Comment by nelsonpecora** [comment]
If you want compatibility with old browsers that didn't support px media queries when you zoomed. This bug was fixed in webkit back in 2013, and I believe works on IE9+

**Comment by gloddy** [comment]
It's not the backwards compatibility that concerns me. It's that Ems tend to zoom better: http://blog.cloudfour.com/the-ems-have-it-proportional-media-queries-ftw/

**Comment by nelsonpecora** [comment]
"You should note that the zooming behavior has long since been made consistent in browsers (i.e. fixed). Keep that in mind if you cite or otherwise put stock in this post." From your link.

**Comment by gloddy** [comment]
I fear a genuine change in zooming behavior by switching this. I suppose the only way to know if to run it once with px out and again with em output and then test across multiple browsers.
That said, I was just looking at giving people the option. Not to change our long-standing not-broken default.

**Comment by nelsonpecora** [comment]
The only change would be if people manually changed their default font size (in their browser settings). In that situation, our em-based breakpoints are probably making the content flow weirdly currently.

**Comment by nelsonpecora** [comment]
Actually, it's not terrible currently, but there are definity wonky things, like these prev-next arrows:

screen shot 2015-03-30 at 3 51 46 pm

**Comment by nelsonpecora** [comment]
Very small, very broken: 
screen shot 2015-03-30 at 3 54 04 pm

**Comment by gloddy** [comment]
Not all browsers use 16 as their default font size. And super small settings aren't what we're concerned about here.

**Comment by nelsonpecora** [comment]
Um...I'm pretty sure all modern browsers use 16px as the default...

Em-based media queries were a response to the webkit bug, but aren't needed anymore.

**Comment by gloddy** [comment]
Kindle Fire doesn't use 16px last I checked.
That said, let's do it and see what happens. Certainly makes the code simpler.

**Comment by nelsonpecora** [comment]
Roger, merging.

**Pull request merged**
